'use client';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useEffect, useRef } from 'react';
import { Archive, LayoutDashboard, ArrowLeftRight, History, Users, Landmark, Wallet, FileOutput, ScanLine, Settings, Moon, Sun, Menu, X, LogOut, ChevronRight, Plus, Layers } from 'lucide-react';
import { useAuth } from './auth-context';
import { useTheme } from './theme-context';
import { Avatar } from './avatar';
const groups = [
 {name:'ESPACE DE TRAVAIL',items:[{href:'/dashboard',label:'Vue d’ensemble',icon:LayoutDashboard},{href:'/conversions',label:'Conversions',icon:ArrowLeftRight},{href:'/conversions/history',label:'Historique',icon:History},{href:'/client-workspace',label:'Espace clients',icon:Archive}]},
 {name:'RÉFÉRENTIELS',items:[{href:'/clients',label:'Clients',icon:Users},{href:'/banks',label:'Banques',icon:Landmark},{href:'/bank-accounts',label:'Comptes bancaires',icon:Wallet}]},
 {name:'CONFIGURATION',items:[{href:'/templates',label:'Modèles d’export',icon:FileOutput},{href:'/extraction-profiles',label:'Profils d’extraction',icon:ScanLine},{href:'/settings',label:'Paramètres',icon:Settings}]}
];
export function AppShell({children}:{children:React.ReactNode}) {
 const pathname=usePathname(); const router=useRouter(); const {isAuthenticated,isReady,user,logout}=useAuth(); const {isLightMode,toggleTheme}=useTheme(); const drawer=useRef<HTMLDialogElement>(null);
 const authRoute=pathname==='/login'||pathname==='/register';
 useEffect(()=>{if(!isReady)return;if(!isAuthenticated&&!authRoute)router.replace('/login');else if(isAuthenticated&&authRoute)router.replace('/dashboard');},[isReady,isAuthenticated,authRoute,router]);
 const active=groups.flatMap(g=>g.items).find(i=>i.href===pathname);
 const navigation=<><Link href="/dashboard" className="brand" onClick={()=>drawer.current?.close()}><span className="brand-mark"><Layers size={23}/></span><span>Releve<span className="accent-text">Flow</span><small>Votre espace comptable</small></span></Link><nav aria-label="Navigation principale" className="sidebar-nav">{groups.map(g=><div key={g.name}><p className="nav-caption">{g.name}</p>{g.items.map(({href,label,icon:Icon})=><Link key={href} href={href} aria-current={pathname===href?'page':undefined} className={`nav-link ${pathname===href?'active':''}`} onClick={()=>drawer.current?.close()}><Icon size={19} strokeWidth={1.7}/><span>{label}</span>{pathname===href&&<ChevronRight size={15} className="ml-auto"/>}</Link>)}</div>)}</nav><div className="sidebar-bottom"><div className="workspace-note"><ScanLine size={20}/><div><strong>Du relevé à l’écriture</strong><p>Importez, vérifiez et exportez.</p></div></div><Link href="/settings" className="sidebar-profile" onClick={()=>drawer.current?.close()}><Avatar name={user?.name||'Utilisateur'}/><span className="min-w-0 flex-1"><strong className="block truncate">{user?.name}</strong><small className="muted">{user?.role==='Admin'?'Administrateur':'Utilisateur'}</small></span><Settings size={17}/></Link><button className="logout-button" onClick={()=>{drawer.current?.close();logout();router.replace('/login');}}><LogOut size={16}/> Se déconnecter</button></div></>;
 if(authRoute)return <>{children}</>;
 if(!isReady||!isAuthenticated)return <div className="app-loading" role="status"><span className="loading-dot"/>Chargement de votre espace…</div>;
 return <div className="app-shell"><a href="#main-content" className="skip-link">Aller au contenu</a><aside className="desktop-sidebar">{navigation}</aside><dialog ref={drawer} className="mobile-drawer"><button className="icon-button drawer-close" aria-label="Fermer le menu" onClick={()=>drawer.current?.close()}><X size={20}/></button>{navigation}</dialog><div className="app-body"><header className="topbar"><div className="flex min-w-0 items-center gap-3"><button className="icon-button mobile-menu" aria-label="Ouvrir le menu" onClick={()=>drawer.current?.showModal()}><Menu size={21}/></button><span className="breadcrumb-root">Espace de travail</span><ChevronRight size={14} className="breadcrumb-root"/><span className="truncate font-medium">{active?.label||'ReleveFlow'}</span></div><div className="flex shrink-0 items-center gap-3"><button className="icon-button" onClick={toggleTheme} aria-label={isLightMode?'Activer le thème sombre':'Activer le thème clair'} title={isLightMode?'Thème sombre':'Thème clair'}>{isLightMode?<Moon size={19}/>:<Sun size={19}/>}</button><Link className="button-primary topbar-create" href="/conversions"><Plus size={17}/> Nouvelle conversion</Link><Link href="/settings" aria-label="Mon profil"><Avatar name={user?.name||'Utilisateur'} small/></Link></div></header><main id="main-content" className="main-content" key={pathname}>{children}</main><footer className="app-footer"><span>ReleveFlow <span className="footer-divider">/</span> Gestion des relevés bancaires</span><Link href="/settings">Mon espace <ChevronRight size={13}/></Link></footer></div></div>;
}
