'use client';
import { useEffect,useState } from 'react';
import { BankDialog } from './bank-dialogs';
import { ConversionSteps, ExportMapping, ConversionReview, standardTransactions } from './conversion-review';
import { all,API_URL,getSession,request,Statement,ExportTemplate,Client,Account,Conversion,download } from '@/services/api';
export type WorkspaceDocument={id:string;clientId:string;bankAccountId:string;bankId:string;status:string;errorMessage:string|null;inputFileName:string;createdAt:string;completedAt:string|null;transactionCount:number;bank:string;account:string;outputFileName:string|null;exportLabel:string|null;hasOriginal:boolean;hasStandard:boolean;hasExport:boolean};
export function ProcessDocument({item,onClose,onSaved}:{item:WorkspaceDocument;onClose:()=>void;onSaved:()=>void}){
 const [result,setResult]=useState<Conversion|null>(null);
 const [profiles,setProfiles]=useState<Statement[]>([]);const [exports,setExports]=useState<ExportTemplate[]>([]);const [profileId,setProfileId]=useState('');const [exportId,setExportId]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{let active=true;Promise.all([all<Statement>('/bank-statement-templates'),all<ExportTemplate>('/export-templates')]).then(([p,e])=>{if(active){setProfiles(p.filter(x=>x.bankId===item.bankId&&x.isActive));setExports(e.filter(x=>x.isActive));}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[item.bankId]);
 async function process(){setBusy(true);setError('');try{const converted=await request<Conversion>(`/documents/${item.id}/process`,{method:'POST',body:JSON.stringify({profileId,exportId})});setResult(converted);onSaved();}catch(e){setError((e as Error).message);onSaved();}finally{setBusy(false);}}
 if(result)return <BankDialog wide title="Résultat de la conversion" onClose={onClose}><ConversionSteps step={2}/><p className="mb-5 break-all font-semibold">{item.inputFileName}</p><ConversionReview transactions={result.transactions} action={<button className="button-primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await download(result.history);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Télécharger l’export</button>}/>{error&&<p role="alert" className="danger-button mt-3">{error}</p>}</BankDialog>;
 return <BankDialog wide title="Configurer la conversion" onClose={onClose} busy={busy}><div className="space-y-5"><ConversionSteps step={1}/><p className="break-all font-semibold">{item.inputFileName}</p><p className="muted text-sm">{item.bank} · {item.account}</p><label className="block"><span className="ui-label">Profil de lecture PDF</span><select className="ui-input" disabled={busy||loading} value={profileId} onChange={e=>setProfileId(e.target.value)}><option value="">Choisir un profil</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="block"><span className="ui-label">Format d’export</span><select className="ui-input" disabled={busy||loading} value={exportId} onChange={e=>setExportId(e.target.value)}><option value="">Choisir un format</option>{exports.map(e=><option key={e.id} value={e.id}>{e.name} · {e.type}</option>)}</select></label>{exports.find(e=>e.id===exportId)&&<ExportMapping template={exports.find(e=>e.id===exportId)!}/>}{!loading&&!profiles.length&&<p className="muted">Aucun profil actif pour cette banque. Configurez-en un dans « Profils d’extraction ».</p>}<p className="muted text-xs">La réussite génère le CSV standard et l’export comptable. Seuls les cinq derniers traitements réussis sont conservés.</p>{busy&&<p role="status">Extraction et génération en cours…</p>}{error&&<p className="danger-button" role="alert">{error} Le PDF reste disponible pour une nouvelle tentative.</p>}<button className="button-primary" disabled={busy||loading||!profileId||!exportId} onClick={process}>{busy?'Traitement…':'Lancer le traitement'}</button></div></BankDialog>;
}
export function DocumentPreview({clientId,item,kind,onClose}:{clientId:string;item:WorkspaceDocument;kind:string;onClose:()=>void}){
 const [url,setUrl]=useState('');const [data,setData]=useState<{rows?:string[][];text?:string;truncated:boolean}|null>(null);const [error,setError]=useState('');
 useEffect(()=>{let active=true;let objectUrl='';const controller=new AbortController();async function load(){try{if(kind==='original'){const response=await fetch(`${API_URL}/client-workspace/${clientId}/archives/${item.id}/files/original`,{headers:{Authorization:`Bearer ${getSession()?.token||''}`},signal:controller.signal});if(!response.ok){if(response.status===401)window.dispatchEvent(new Event('session-expired'));throw Error('PDF indisponible.');}objectUrl=URL.createObjectURL(await response.blob());if(active)setUrl(objectUrl);else URL.revokeObjectURL(objectUrl);}else{const result=await request<{rows?:string[][];text?:string;truncated:boolean}>(`/client-workspace/${clientId}/archives/${item.id}/preview/${kind}`,{signal:controller.signal});if(active)setData(result);}}catch(e){if(active)setError((e as Error).message);}}void load();return()=>{active=false;controller.abort();if(objectUrl)URL.revokeObjectURL(objectUrl);};},[clientId,item.id,kind]);
 return <BankDialog wide={kind!=='original'} title={kind==='original'?'Consulter le PDF':kind==='standard'?'Analyse des transactions':'Consulter l’export'} onClose={onClose}><p className="mb-4 break-all text-sm">{item.inputFileName}</p>{error&&<p className="danger-button" role="alert">{error}</p>}{!error&&!url&&!data&&<p role="status">Chargement de l’aperçu…</p>}{url&&<><iframe title="Aperçu du relevé PDF" src={url} className="h-[60vh] w-full rounded-lg border border-[var(--border)]"/><a href={url} target="_blank" rel="noreferrer" className="button-secondary mt-3">Ouvrir le PDF dans un nouvel onglet</a></>}{data?.rows&&kind==='standard'&&<><ConversionReview transactions={standardTransactions(data.rows)} truncated={data.truncated}/><details className="mt-5"><summary className="accent-text cursor-pointer text-sm">Toutes les colonnes du CSV standard</summary><div className="max-h-[40vh] overflow-auto mt-3"><table className="conversion-table"><thead><tr>{data.rows[0]?.map((cell,j)=><th scope="col" key={j}>{cell}</th>)}</tr></thead><tbody>{data.rows.slice(1).map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell||'—'}</td>)}</tr>)}</tbody></table></div></details></>}{data?.rows&&kind!=='standard'&&<div className="max-h-[60vh] overflow-auto"><table className="min-w-full text-left text-xs"><tbody>{data.rows.map((row,i)=><tr key={i} className="ui-table-row">{row.map((cell,j)=><td key={j} className="whitespace-pre-wrap px-3 py-2">{cell}</td>)}</tr>)}</tbody></table></div>}{data?.text!==undefined&&<pre className="max-h-[60vh] overflow-auto rounded-lg bg-[var(--surface-alt)] p-4 text-xs">{data.text}</pre>}{data?.truncated&&<p className="ui-description">Aperçu limité aux 500 premières lignes ou 100 000 caractères. Téléchargez le fichier pour consulter son contenu complet.</p>}</BankDialog>;
}

export function ManageDocument({item,remove,onClose,onSaved}:{item:WorkspaceDocument;remove:boolean;onClose:()=>void;onSaved:()=>void}){
 const [clients,setClients]=useState<Client[]>([]);const [accounts,setAccounts]=useState<Account[]>([]);const [clientId,setClientId]=useState(item.clientId);const [accountId,setAccountId]=useState(item.bankAccountId);const [file,setFile]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(!remove);const [error,setError]=useState('');
 useEffect(()=>{if(remove)return;let active=true;Promise.all([all<Client>('/clients'),all<Account>('/bank-accounts')]).then(([c,a])=>{if(active){setClients(c);setAccounts(a);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[remove]);
 async function save(){setBusy(true);setError('');try{if(remove)await request('/documents/'+item.id,{method:'DELETE'});else{const form=new FormData();form.append('clientId',clientId);form.append('bankAccountId',accountId);if(file)form.append('file',file);await request('/documents/'+item.id,{method:'PUT',body:form});}onSaved();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <BankDialog title={remove?'Supprimer le relevé':'Modifier le relevé'} onClose={onClose} busy={busy}><div className="space-y-5"><p className="break-all font-semibold">{item.inputFileName}</p>{remove?<p>Supprimer définitivement ce dossier et tous ses fichiers (PDF, CSV standard et export) ? Cette action est irréversible.</p>:<fieldset disabled={busy||loading} className="space-y-4"><label className="block"><span className="ui-label">Client</span><select className="ui-input" value={clientId} onChange={e=>{setClientId(e.target.value);setAccountId('');}}>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="block"><span className="ui-label">Compte bancaire</span><select className="ui-input" value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Choisir un compte</option>{accounts.filter(a=>a.clientId===clientId).map(a=><option key={a.id} value={a.id}>{a.bank} · {a.accountNumber}</option>)}</select></label><label className="block"><span className="ui-label">Remplacer le PDF (facultatif)</span><input type="file" accept="application/pdf" className="ui-file" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><p className="muted text-xs">Sans nouveau fichier, le PDF actuel est conservé. Le dossier revient en attente de traitement. Si le client change, retrouvez-le dans l’espace du nouveau client.</p></fieldset>}{error&&<p role="alert" className="danger-button">{error}</p>}<div className="flex justify-end gap-3"><button className="button-secondary" disabled={busy} onClick={onClose}>Annuler</button><button className={remove?'button-secondary danger-button':'button-primary'} disabled={busy||loading||(!remove&&(!clientId||!accountId))} onClick={save}>{busy?'En cours…':remove?'Confirmer la suppression':'Enregistrer'}</button></div></div></BankDialog>;
}
