export const pageTheme = {
  "page": "ui-page",
  "hero": "ui-hero",
  "chip": "ui-eyebrow",
  "title": "ui-title",
  "button": "button-primary",
  "card": "ui-card",
  "row": "ui-row",
  "rowLabel": "muted",
  "rowValue": "ui-value",
  "tag": "ui-tag",
  "meta": "muted text-sm",
  "label": "ui-label",
  "input": "ui-input",
  "select": "ui-input",
  "step": "ui-tag",
  "stepActive": "accent-text",
  "stepIdle": "muted",
  "upload": "ui-upload",
  "uploadText": "font-semibold",
  "uploadHint": "ui-description",
  "uploadButton": "button-secondary",
  "fileInput": "ui-file",
  "summaryCard": "ui-summary",
  "summaryLabel": "muted text-xs",
  "summaryValue": "metric-value",
  "tableHead": "ui-table-head",
  "tableCell": "ui-table-cell",
  "tableRow": "ui-table-row",
  "head": "ui-table-head",
  "cell": "ui-table-cell",
  "status": "ui-tag",
  "stat": "ui-summary",
  "statLabel": "muted text-xs",
  "statValue": "metric-value",
  "item": "ui-row",
  "itemLabel": "muted",
  "itemValue": "ui-value",
  "value": "ui-value",
  "listCard": "ui-card",
  "itemTitle": "font-semibold",
  "itemMeta": "muted text-xs",
  "itemTime": "muted text-xs"
} as const;
