'use client';
import { useCatalog } from '@/services/use-catalog';
import { useState } from 'react';
import Link from 'next/link';
import { Client,Account } from '@/services/api';
import { LoadState } from '@/components/resource-editor';
import { StatementList } from '@/components/statement-list';
export default function ClientSpace(){
 const {data,error,loading}=useCatalog<Client>('/clients');const {data:accounts}=useCatalog<Account>('/bank-accounts');const [id,setId]=useState('');const [account,setAccount]=useState('');const [tab,setTab]=useState('statements');const client=data?.items.find(c=>c.id===id);
 return <div className="ui-page"><section className="ui-hero"><p className="ui-eyebrow">DOSSIER CLIENT</p><h1 className="ui-title">Espace clients</h1><p className="ui-description">Informations, comptes bancaires, relevés et exports conservés.</p></section><LoadState error={error} loading={loading}/><label>Choisir un client<select className="ui-input mt-2" value={id} onChange={e=>{setId(e.target.value);setAccount('');}}><option value="">Sélectionnez un client</option>{data?.items.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{client&&<><section className="ui-card"><h2 className="text-lg font-semibold">{client.name}</h2><p className="ui-description">{client.legalName}</p><div className="grid gap-3 sm:grid-cols-2 mt-4">{[['ICE',client.ice],['IF',client.if],['RC',client.rc],['E-mail',client.email],['Téléphone',client.phone],['Pays',client.country]].map(([label,value])=><div className="ui-row" key={label}><span className="muted">{label}</span><span>{value||'—'}</span></div>)}</div><p className="ui-description">Banques : {client.banks.join(', ')||'Aucune'}</p></section><div className="flex flex-wrap gap-3"><label className="flex-1">Compte bancaire<select className="ui-input mt-2" value={account} onChange={e=>setAccount(e.target.value)}><option value="">Tous les comptes</option>{accounts?.items.filter(a=>a.clientId===id).map(a=><option key={a.id} value={a.id}>{a.bank} · {a.accountNumber} · {a.currency}</option>)}</select></label><label>Vue<select className="ui-input mt-2" value={tab} onChange={e=>setTab(e.target.value)}><option value="statements">Tous les relevés et exports</option><option value="archives">Archives validées</option></select></label></div><Link href="/conversions" className="button-primary justify-self-start">Importer un relevé</Link><StatementList key={id+account+tab} clientId={id} accountId={account} archived={tab==='archives'}/></>}</div>;
}

