'use client';
import { use, useEffect, useState } from 'react';
import Link from 'next/link';
import { Download, Plus, Trash2, Save, Check, Archive, Play } from 'lucide-react';
import { Detail, Template, Transaction, download, statusLabel } from '@/services/statements';
import { request } from '@/services/api';
import { useApi } from '@/services/use-api';
import { useAuth } from '@/components/auth-context';
import { LoadState } from '@/components/resource-editor';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
const blank:Transaction={transactionDate:null,valueDate:null,reference:'',description:'',debit:null,credit:null,balance:null};
function Review({detail,onSaved}:{detail:Detail;onSaved:()=>void}){
 const {can}=useAuth();const [rows,setRows]=useState(detail.transactions);const [start,setStart]=useState(detail.periodStart||'');const [end,setEnd]=useState(detail.periodEnd||'');const [opening,setOpening]=useState(detail.openingBalance?.toString()??'');const [closing,setClosing]=useState(detail.closingBalance?.toString()??'');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const locked=detail.pageCount===0||!!detail.archivedAt||['QUEUED','ANALYZING','OCR_PROCESSING'].includes(detail.status)||!can('statements.write');
 const number=(s:string)=>s.trim()===''?null:Number(s);
 async function save(){setBusy(true);setError('');try{await request(`/statements/${detail.id}/review`,{method:'PUT',body:JSON.stringify({version:detail.version,periodStart:start||null,periodEnd:end||null,openingBalance:number(opening),closingBalance:number(closing),transactions:rows})});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function update(index:number,key:keyof Transaction,value:string){setRows(prev=>prev.map((row,i)=>i===index?{...row,[key]:['debit','credit','balance'].includes(key)?number(value):value||(['transactionDate','valueDate'].includes(key)?null:'')}:row));}
 return <section className="ui-card"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-lg font-semibold">Revue des opérations</h2><p className="ui-description">Vérifiez avec le PDF original. Enregistrer une correction annule la validation précédente.</p></div><Button className="button-primary" disabled={locked||busy} onClick={save}><Save size={15}/>{busy?'Enregistrement…':'Enregistrer la revue'}</Button></div><fieldset disabled={locked||busy}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 my-5">{[['Début de période',start,setStart,'date'],['Fin de période',end,setEnd,'date'],['Solde initial',opening,setOpening,'number'],['Solde final',closing,setClosing,'number']].map(([label,value,set,type])=><label className="text-sm" key={String(label)}>{String(label)}<Input className="ui-input mt-2" type={String(type)} step="0.01" value={String(value)} onChange={e=>(set as (s:string)=>void)(e.target.value)}/></label>)}</div><div className="overflow-x-auto"><table className="statement-table"><thead><tr>{['Date','Date valeur','Référence','Libellé','Débit','Crédit','Solde',''].map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{(['transactionDate','valueDate','reference','description','debit','credit','balance'] as const).map(key=><td key={key}><Input aria-label={`${key} ligne ${i+1}`} type={key.includes('Date')?'date':['debit','credit','balance'].includes(key)?'number':'text'} step="0.01" className={`ui-input ${key==='description'?'min-w-60':'min-w-32'}`} value={row[key]??''} onChange={e=>update(i,key,e.target.value)}/></td>)}<td><Button size="icon" variant="ghost" aria-label={`Supprimer la ligne ${i+1}`} onClick={()=>setRows(rows.filter((_,j)=>i!==j))}><Trash2 size={15}/></Button></td></tr>)}</tbody></table></div><Button className="button-secondary mt-4" onClick={()=>setRows([...rows,{...blank}])} disabled={rows.length>=10000}><Plus size={15}/>Ajouter une opération</Button></fieldset>{error&&<p role="alert" className="danger-button mt-4">{error}</p>}</section>;
}
export default function StatementDetail({params}:{params:Promise<{id:string}>}){
 const {id}=use(params);const {can}=useAuth();const {data:s,error,loading,reload}=useApi<Detail>('/statements/'+id);const {data:templates}=useApi<Template[]>('/export-templates');const {data:profiles}=useApi<{id:string;bankId:string;name:string;isActive:boolean}[]>('/statement-profiles');
 const [profile,setProfile]=useState('');const [template,setTemplate]=useState('');const [busy,setBusy]=useState(false);const [actionError,setActionError]=useState('');const [preview,setPreview]=useState('');const [notice,setNotice]=useState('');
 const processing=!!s&&['QUEUED','ANALYZING','OCR_PROCESSING'].includes(s.status);
 useEffect(()=>{if(!processing)return;const timer=setInterval(reload,2500);return()=>clearInterval(timer);},[processing,reload]);
 async function action(path:string,body:object={}){if(!s||busy)return;setBusy(true);setActionError('');setNotice('');try{await request(`/statements/${id}/${path}`,{method:'POST',body:JSON.stringify({version:s.version,...body})});setNotice('Action enregistrée.');setPreview('');reload();}catch(e){setActionError((e as Error).message);}finally{setBusy(false);}}
 async function getFile(path:string,name:string){try{await download(path,name);}catch(e){setActionError((e as Error).message);}}
 async function showPreview(){if(!s)return;setBusy(true);setActionError('');try{const r=await request<{text:string}>(`/statements/${id}/export-preview`,{method:'POST',body:JSON.stringify({version:s.version,templateId:template})});setPreview(r.text);}catch(e){setActionError((e as Error).message);}finally{setBusy(false);}}
 if(!s)return <LoadState error={error} loading={loading}/>;
 return <div className="ui-page"><section className="ui-hero"><Link href="/conversions" className="muted text-xs">← Conversions et relevés</Link><div className="flex flex-wrap items-center justify-between gap-4 mt-3"><div><h1 className="ui-title break-all">{s.originalFileName}</h1><p className="ui-description">{s.client} · {s.bank} · {s.account} · {s.currency}</p></div><span className="ui-tag">{statusLabel[s.status]||s.status}</span></div><p className="ui-description">{s.message}</p><Button className="button-secondary mt-4" onClick={()=>getFile(`/statements/${id}/pdf`,s.originalFileName)}><Download size={15}/>PDF original</Button></section><LoadState error={error||actionError} loading={processing}/>{notice&&<p role="status" className="ui-summary">{notice}</p>}
 {!s.transactions.length&&!s.archivedAt&&can('statements.write')&&<section className="ui-card flex flex-wrap items-end gap-4"><label className="flex-1">Profil bancaire<select className="ui-input mt-2" value={profile} onChange={e=>setProfile(e.target.value)}><option value="">Détection automatique</option>{profiles?.filter(p=>p.isActive&&p.bankId===s.bankId).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><Button className="button-primary" disabled={busy||processing} onClick={()=>action('process',{profileId:profile||null})}><Play size={15}/>Analyser / relancer</Button><p className="ui-description w-full">Sans profil bancaire vérifié, le format reste inconnu. Vous pouvez consulter le texte et saisir les opérations manuellement.</p></section>}
 <section className="ui-card"><h2 className="font-semibold">Contrôles du relevé</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 mt-4">{[['Débits',s.check.totalDebit],['Crédits',s.check.totalCredit],['Solde calculé',s.check.calculatedBalance],['Écart',s.check.difference]].map(([label,value])=><div className="ui-summary" key={label}><p className="muted text-xs">{label}</p><p className="text-xl font-semibold mt-2">{value===null?'—':Number(value).toLocaleString('fr-FR',{minimumFractionDigits:2})}</p></div>)}</div>{s.overlappingPeriod&&<p className="danger-button mt-3">Un autre relevé couvre la même période : vérifiez le doublon.</p>}<ul className="mt-4 space-y-2 text-sm">{s.check.issues.map((issue,i)=><li className="danger-button" key={i}>{issue.row?`Ligne ${issue.row} : `:''}{issue.message}</li>)}</ul>{can('statements.write')&&!s.archivedAt&&<Button className="button-primary mt-4" disabled={busy||processing||!!s.check.issues.length||!!s.validatedAt} onClick={()=>action('validate')}><Check size={15}/>Valider les données enregistrées</Button>}</section>
 <Review key={s.version} detail={s} onSaved={reload}/>
 <section className="ui-card"><h2 className="text-lg font-semibold">Génération des exports</h2><p className="ui-description">Les modèles Sage doivent correspondre au paramétrage de votre installation. Aucun retraitement du PDF n’est nécessaire.</p><div className="flex flex-wrap items-end gap-3 mt-4"><label className="flex-1">Modèle<select className="ui-input mt-2" value={template} onChange={e=>{setTemplate(e.target.value);setPreview('');}}><option value="">Choisir un modèle</option>{templates?.filter(t=>t.isActive).map(t=><option key={t.id} value={t.id}>{t.name} · {t.encoding}</option>)}</select></label><Button className="button-secondary" disabled={!template||busy||processing} onClick={showPreview}>Aperçu (10 lignes)</Button>{can('statements.write')&&<Button className="button-primary" disabled={!template||busy||processing||!s.validatedAt} onClick={()=>action('exports',{templateId:template})}>Générer et conserver</Button>}</div>{preview&&<pre className="ui-summary overflow-auto text-xs mt-4">{preview}</pre>}<div className="mt-5 space-y-3">{s.exports.map(e=><div className="ui-row" key={e.id}><span className="break-all">{e.fileName}<small className="muted block">{new Date(e.createdAt).toLocaleString('fr-FR')} · {e.fileSize} octets</small></span><Button className="button-secondary" onClick={()=>getFile(`/statement-exports/${e.id}/download`,e.fileName)}><Download size={15}/>Télécharger</Button></div>)}</div></section>
 <section className="ui-card"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-lg font-semibold">Historique du traitement</h2>{!s.archivedAt&&can('statements.write')&&<Button className="button-secondary" disabled={busy||processing||!s.validatedAt} onClick={()=>action('archive')}><Archive size={15}/>Archiver le relevé</Button>}</div><ol className="statement-timeline mt-5">{s.history.map(h=><li key={h.id}><p className="font-medium">{h.message}</p><small className="muted">{h.action} · {new Date(h.createdAt).toLocaleString('fr-FR')}</small></li>)}</ol></section>{s.rawText&&<details className="ui-card"><summary className="cursor-pointer font-semibold">Texte extrait pour la revue</summary><pre className="mt-4 whitespace-pre-wrap break-all text-xs max-h-96 overflow-auto">{s.rawText}</pre></details>}</div>;
}

