'use client';
import Link from 'next/link';
import { ConversionSteps } from '@/components/conversion-review';
import { useEffect,useState } from 'react';
import { Upload } from 'lucide-react';
import { all, Account, Client, History, request } from '@/services/api';
export default function ConversionsPage(){
 const [clients,setClients]=useState<Client[]>([]);const [accounts,setAccounts]=useState<Account[]>([]);const [clientId,setClientId]=useState('');const [accountId,setAccountId]=useState('');const [file,setFile]=useState<File|null>(null);const [result,setResult]=useState<History|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{let active=true;Promise.all([all<Client>('/clients'),all<Account>('/bank-accounts')]).then(([c,a])=>{if(active){setClients(c);setAccounts(a);const selected=new URLSearchParams(window.location.search).get('clientId');if(c.some(x=>x.id===selected))setClientId(selected!);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 async function upload(){if(!file)return;setBusy(true);setError('');setResult(null);try{const form=new FormData();form.append('clientId',clientId);form.append('bankAccountId',accountId);form.append('file',file);setResult(await request<History>('/documents',{method:'POST',body:form}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="ui-page"><section className="ui-hero"><p className="ui-eyebrow">ÉTAPE 1 · IMPORTATION</p><h1 className="ui-title">Importer un relevé PDF</h1><p className="ui-description">Enregistrez le document du client. Le profil de lecture et le format d’export seront choisis ensuite dans son espace.</p></section><ConversionSteps step={0}/><section className="ui-card"><fieldset disabled={loading||busy} className="grid gap-6 lg:grid-cols-2"><div className="space-y-5"><label className="block"><span className="ui-label">Client</span><select className="ui-input" value={clientId} onChange={e=>{setClientId(e.target.value);setAccountId('');setResult(null);}}><option value="">Choisir un client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name} — {c.legalName}</option>)}</select></label><label className="block"><span className="ui-label">Compte bancaire</span><select className="ui-input" value={accountId} onChange={e=>{setAccountId(e.target.value);setResult(null);}}><option value="">Choisir un compte</option>{accounts.filter(a=>a.clientId===clientId).map(a=><option key={a.id} value={a.id}>{a.bank} · {a.accountNumber} ({a.currency})</option>)}</select></label><p className="ui-description">Le PDF sera immédiatement consultable avec le statut « En attente de traitement ».</p></div><div className="ui-upload"><Upload className="accent-text mb-4" size={30}/><h2 className="font-semibold">Choisir un relevé PDF</h2><p className="ui-description">PDF · 20 Mo maximum</p><input aria-label="Relevé PDF" type="file" accept="application/pdf" className="ui-file" onChange={e=>{setFile(e.target.files?.[0]||null);setResult(null);}}/><button className="button-primary mt-5" disabled={!file||!clientId||!accountId||busy||!!result} onClick={upload}>{busy?'Importation…':'Importer le relevé'}</button></div></fieldset>{loading&&<p role="status">Chargement…</p>}{error&&<p role="alert" className="danger-button mt-5">{error}</p>}</section>{result&&<section className="ui-card"><span className="status-positive">PDF importé</span><h2 className="mt-4 font-semibold">En attente de traitement</h2><p className="ui-description">{result.inputFileName} est enregistré. Vous pouvez le consulter et configurer son traitement.</p><Link className="button-primary mt-4" href={`/client-workspace?clientId=${result.clientId}`}>Ouvrir l’espace client →</Link></section>}</div>;
}
