'use client';
import Link from 'next/link';
import { Users, Landmark, CheckCheck, CircleAlert, ArrowUpRight, FileUp, ScanLine, FileOutput, ArrowRight, FileText } from 'lucide-react';
import { Dashboard } from '@/services/api';
import { useApi } from '@/services/use-api';
import { useAuth } from '@/components/auth-context';
import { LoadState } from '@/components/resource-editor';
import { Avatar } from '@/components/avatar';
export default function DashboardPage(){
 const {data,error,loading}=useApi<Dashboard>('/dashboard');const {user}=useAuth();
 const metrics=[{label:'Clients',value:data?.clients,icon:Users,href:'/clients',note:'Votre portefeuille clients'},{label:'Banques',value:data?.banks,icon:Landmark,href:'/banks',note:'Dans votre référentiel'},{label:'Conversions réussies',value:data?.completed,icon:CheckCheck,href:'/conversions/history',note:'Fichiers traités avec succès'},{label:'Conversions échouées',value:data?.failed,icon:CircleAlert,href:'/conversions/history',note:'À consulter dans l’historique'}];
 return <div className="ui-page"><section className="ui-hero flex flex-wrap items-center justify-between gap-5"><div><p className="ui-eyebrow">TABLEAU DE BORD</p><h1 className="ui-title">Bonjour, {user?.name?.split(' ')[0]||'bienvenue'} <span className="accent-text">.</span></h1><p className="ui-description">Une vue claire sur vos clients et le traitement de vos relevés.</p></div><Link className="button-primary" href="/conversions"><FileUp size={17}/> Importer un relevé</Link></section><LoadState error={error} loading={loading}/>
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({label,value,icon:Icon,href,note})=><Link href={href} key={label} className="ui-card client-card"><div className="flex items-center justify-between"><span className="metric-icon"><Icon size={21}/></span><ArrowUpRight size={16} className="muted"/></div><p className="metric-value">{value??'—'}</p><h2 className="mt-1 text-xs font-semibold">{label}</h2><p className="muted mt-3 text-[11px]">{note}</p></Link>)}</section>
 <section className="grid items-start gap-5 xl:grid-cols-[minmax(0,2fr)_minmax(260px,1fr)]"><div className="ui-card"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">Conversions récentes</h2><p className="muted mt-1 text-xs">Suivez vos derniers traitements.</p></div><Link href="/conversions/history" className="accent-text flex items-center gap-2 text-xs font-semibold">Tout voir <ArrowRight size={14}/></Link></div>{!loading&&!error&&!data?.recent.length&&<div className="load-state flex-col"><FileText size={27}/><p>Aucune conversion pour le moment.</p><Link href="/conversions" className="button-secondary">Importer votre premier relevé</Link></div>}<div className="space-y-1">{data?.recent.map(item=><Link key={item.id} href="/conversions/history" className="ui-row py-4"><div className="flex min-w-0 items-center gap-3"><Avatar name={item.client} small/><div className="min-w-0"><p className="truncate font-semibold">{item.client}</p><p className="muted mt-1 truncate text-[11px]">{item.bank} · {new Date(item.createdAt).toLocaleDateString('fr-FR')}</p></div></div><div className="shrink-0 text-right"><span className={item.status==='Completed'?'status-positive':'ui-tag'}>{item.status==='Completed'?'Terminée':item.status==='Failed'?'Échouée':item.status==='Pending'?'En attente':'En cours'}</span><p className="muted mt-2 text-[10px]">{item.count} opérations</p></div></Link>)}</div></div>
 <div className="ui-card"><span className="ui-eyebrow">VOTRE PARCOURS</span><h2 className="mt-3 text-lg font-bold">Du PDF à votre export</h2><p className="ui-description">Trois étapes pour préparer vos données comptables.</p><div className="mt-6 space-y-6">{[{icon:FileUp,title:'01 · Importer',text:'Choisissez le client, le compte et son relevé PDF.'},{icon:ScanLine,title:'02 · Vérifier',text:'Consultez les opérations extraites avec votre profil de lecture.'},{icon:FileOutput,title:'03 · Exporter',text:'Téléchargez le fichier dans le format comptable configuré.'}].map(({icon:Icon,title,text})=><div key={title} className="flex items-start gap-3"><span className="metric-icon"><Icon size={17}/></span><div><h3 className="text-xs font-semibold">{title}</h3><p className="muted mt-2 text-xs leading-5">{text}</p></div></div>)}</div><Link href="/conversions" className="button-secondary mt-7 w-full">Commencer <ArrowRight size={15}/></Link></div></section></div>;
}
