import { API_URL, getSession } from './api';
export type Statement = { id:string; bankAccountId:string; clientId:string; client:string; bank:string; bankId:string; account:string; originalFileName:string; currency:string; status:string; transactionCount:number; exportCount:number; createdAt:string; archivedAt:string|null; version:string; periodStart:string|null; periodEnd:string|null };
export type Transaction = { id?:string; transactionDate:string|null; valueDate:string|null; reference:string; description:string; debit:number|null; credit:number|null; balance:number|null };
export type Field = {sourceField:string; outputField:string; position:number; required:boolean; defaultValue:string};
export type Template = {id:string; name:string; code:string; type:string; encoding:string; delimiter:string; dateFormat:string; decimalSeparator:string; decimals:number; includeHeader:boolean; isActive:boolean; version:string; fields:Field[]};
export type Detail = Statement & {archiveCount:number; archiveLimit:number; message:string; pageCount:number; pdfType:string; openingBalance:number|null; closingBalance:number|null; validatedAt:string|null; profileId:string|null; rawText:string; overlappingPeriod:boolean; transactions:Transaction[]; check:{totalDebit:number;totalCredit:number;calculatedBalance:number|null;difference:number|null;issues:{code:string;message:string;row:number|null}[]}; history:{id:string;action:string;status:string;message:string;createdAt:string}[]; exports:{id:string;fileName:string;fileSize:number;createdAt:string}[]};
export const statusLabel:Record<string,string>={UPLOADED:'Importé',QUEUED:'En attente',ANALYZING:'En cours · analyse',OCR_PROCESSING:'En cours · lecture du document',UNKNOWN_FORMAT:'À vérifier · format inconnu',REVIEW_REQUIRED:'À vérifier',VALIDATED:'Validé',EXPORTED:'Exporté',ARCHIVED:'Archivé',EXTRACTION_FAILED:'Échoué · extraction',OCR_FAILED:'Échoué · lecture du document',VALIDATION_FAILED:'Erreur de validation',EXPORT_FAILED:'Erreur d’export'};
export const actionLabel:Record<string,string>={PDF_UPLOADED:'Import du PDF',PROCESS_QUEUED:'Mise en attente',PDF_ANALYZED:'Analyse du PDF',BANK_DETECTED:'Reconnaissance du profil',OCR_STARTED:'Lecture du document en cours',OCR_COMPLETED:'Lecture du document terminée',TRANSACTIONS_EXTRACTED:'Extraction des opérations',TRANSACTIONS_UPDATED:'Correction des opérations',PROCESS_COMPLETED:'Traitement terminé',STATEMENT_VALIDATED:'Validation du relevé',EXPORT_COMPLETED:'Génération du fichier',STATEMENT_ARCHIVED:'Archivage',STATEMENT_REOPENED:'Réouverture de l’archive',EXTRACTION_FAILED:'Échec de l’extraction',OCR_FAILED:'Échec de la lecture',VALIDATION_FAILED:'Validation refusée',EXPORT_FAILED:'Échec de l’export'};
export const sourceLabel:Record<string,string>={Date:'Date',ValueDate:'Date de valeur',Reference:'Référence',Description:'Libellé',Debit:'Débit',Credit:'Crédit',Amount:'Montant',Balance:'Solde',Account:'Compte',Bank:'Banque',Client:'Client',Currency:'Devise',Journal:'Journal',Direction:'Sens',Analytic:'Analytique'};
export const templateLabel:Record<string,string>={SAGE100_STANDARD:'Sage 100 – Standard',SAGE_X3:'Sage X3 – Import Banque',CUSTOM_CSV:'CSV personnalisé'};
export async function fileBlob(path:string,signal?:AbortSignal) {
 const response=await fetch(API_URL+path,{headers:{Authorization:`Bearer ${getSession()?.token??''}`},signal,cache:'no-store'});
 if(!response.ok){if(response.status===401)window.dispatchEvent(new Event('session-expired'));const problem=await response.json().catch(()=>null);throw new Error(problem?.title||'Fichier inaccessible ou accès refusé.');}
 return response.blob();
}
export async function download(path:string,name:string) {
 const url=URL.createObjectURL(await fileBlob(path));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);
}
